### ISSUE TITLE
WriteInputTS for Misc Gen

### ISSUE THREAD

**Issue by ghost** [rte-antares-rpackage/antaresEditObject#33]
Dear all, 

As far as I know, it is not possible to write input TS for Misc generation using the anatresEditObject functions. 
The text files to be modified are located in "Antares_study/input/misc-gen/"
I could not modify these text files because when reading an already filled misc gen text file, it look like it is not a normal text file : 
That's how it looks like : 
![image](https://user-images.githubusercontent.com/56552654/91425790-e8957b80-e85b-11ea-8602-140bb7033611.png)

My question is : is it possible to make the miscgen-area.txt files support dataframes  so that users can modify them easily? the dataframe head would be for example : 
![image](https://user-images.githubusercontent.com/56552654/91426096-55a91100-e85c-11ea-83c4-7e5438bdee79.png)

Best regards, 
Mahmoud

**Comment by MahmoudMobir** [comment]
Update : This issue could be closed as I managed to create a function that does so. I started from the writeInputTS function and modified so that is fits for misc generation. 
As I don't have push access to this repo, here's my code : 

writeMiscGen = function (area, type = c("miscgen" ), data, overwrite = TRUE, opts = antaresRead::simOptions()) 
{
  type <- match.arg(type)
  assertthat::assert_that(class(opts) == "simOptions")
  if (!tolower(area) %in% opts$areaList) 
    stop(paste(area, "is not a valid area"), call. = FALSE)
  inputPath <- opts$inputPath
  assertthat::assert_that(!is.null(inputPath) && file.exists(inputPath))
  if (type %in% c("miscgen")) {
    values_file <- file.path(inputPath, "misc-gen", paste0(type, 
                                                               "-", tolower(area), ".txt"))
  }
  if (isTRUE(file.size(values_file) > 0) && !overwrite) 
    stop("Time series already exist for this area. Use overwrite=TRUE if you want to overwrite them.", 
         call. = FALSE)
  if (type %in% c("miscgen")) {
    if (NROW(data) != 8760) 
      stop("'data' must be a 8760*N matrix.", call. = FALSE)
  }
  fwrite(x = as.data.table(data), row.names = FALSE, col.names = FALSE, 
         sep = "\t", file = values_file)
}

BR, 
Mahmoud

**Comment by pvictor** [comment]
Hello Mahmoud,

Don't hesitate to create a pull request to add this function.

Victor
